// Mock data simulating backend API responses
import type { Farmer, Buyer, Produce, Message, Conversation } from "./types"

// Mock Users
export const mockFarmers: Farmer[] = [
  {
    id: "f1",
    email: "john@farmer.com",
    password: "password123",
    role: "farmer",
    name: "John Kamara",
    phone: "+232 76 123 456",
    location: "Makeni, Bombali District",
    farmSize: "5 acres",
    farmingExperience: "10 years",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "f2",
    email: "fatmata@farmer.com",
    password: "password123",
    role: "farmer",
    name: "Fatmata Sesay",
    phone: "+232 77 234 567",
    location: "Bo, Southern Province",
    farmSize: "3 acres",
    farmingExperience: "7 years",
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "f3",
    email: "mohamed@farmer.com",
    password: "password123",
    role: "farmer",
    name: "Mohamed Bangura",
    phone: "+232 78 345 678",
    location: "Kenema, Eastern Province",
    farmSize: "8 acres",
    farmingExperience: "15 years",
    createdAt: "2024-03-10T10:00:00Z",
  },
]

export const mockBuyers: Buyer[] = [
  {
    id: "b1",
    email: "sarah@buyer.com",
    password: "password123",
    role: "buyer",
    name: "Sarah Koroma",
    phone: "+232 79 456 789",
    location: "Freetown, Western Area",
    businessName: "Fresh Mart",
    businessType: "Retail Store",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "b2",
    email: "abdul@buyer.com",
    password: "password123",
    role: "buyer",
    name: "Abdul Jalloh",
    phone: "+232 76 567 890",
    location: "Freetown, Western Area",
    businessName: "City Restaurant",
    businessType: "Restaurant",
    createdAt: "2024-02-15T10:00:00Z",
  },
]

// Mock Produce Listings
export const mockProduce: Produce[] = [
  {
    id: "p1",
    farmerId: "f1",
    farmerName: "John Kamara",
    farmerLocation: "Makeni, Bombali District",
    farmerPhone: "+232 76 123 456",
    name: "Rice",
    category: "Grains",
    quantity: "500",
    unit: "kg",
    pricePerUnit: 8000,
    description: "Premium quality locally grown rice. Fresh harvest, properly dried and cleaned.",
    harvestDate: "2024-12-15",
    imageUrl: "/rice-grain-bags.jpg",
    status: "available",
    createdAt: "2024-12-20T10:00:00Z",
  },
  {
    id: "p2",
    farmerId: "f2",
    farmerName: "Fatmata Sesay",
    farmerLocation: "Bo, Southern Province",
    farmerPhone: "+232 77 234 567",
    name: "Cassava",
    category: "Tubers",
    quantity: "300",
    unit: "kg",
    pricePerUnit: 3000,
    description: "Fresh cassava tubers, perfect for gari or fufu. Harvested this week.",
    harvestDate: "2024-12-18",
    imageUrl: "/fresh-cassava-tubers.jpg",
    status: "available",
    createdAt: "2024-12-19T10:00:00Z",
  },
  {
    id: "p3",
    farmerId: "f1",
    farmerName: "John Kamara",
    farmerLocation: "Makeni, Bombali District",
    farmerPhone: "+232 76 123 456",
    name: "Groundnuts",
    category: "Legumes",
    quantity: "200",
    unit: "kg",
    pricePerUnit: 12000,
    description: "High-quality groundnuts, dried and ready for sale. Great for making groundnut paste.",
    harvestDate: "2024-12-10",
    imageUrl: "/groundnuts-peanuts.jpg",
    status: "available",
    createdAt: "2024-12-18T10:00:00Z",
  },
  {
    id: "p4",
    farmerId: "f3",
    farmerName: "Mohamed Bangura",
    farmerLocation: "Kenema, Eastern Province",
    farmerPhone: "+232 78 345 678",
    name: "Tomatoes",
    category: "Vegetables",
    quantity: "150",
    unit: "kg",
    pricePerUnit: 6000,
    description: "Fresh red tomatoes, perfect for cooking. Delivered daily.",
    harvestDate: "2024-12-22",
    imageUrl: "/fresh-red-tomatoes.jpg",
    status: "available",
    createdAt: "2024-12-22T10:00:00Z",
  },
  {
    id: "p5",
    farmerId: "f2",
    farmerName: "Fatmata Sesay",
    farmerLocation: "Bo, Southern Province",
    farmerPhone: "+232 77 234 567",
    name: "Palm Oil",
    category: "Oil",
    quantity: "100",
    unit: "liters",
    pricePerUnit: 15000,
    description: "Pure red palm oil, locally produced. No additives or preservatives.",
    harvestDate: "2024-12-12",
    imageUrl: "/red-palm-oil-bottle.jpg",
    status: "available",
    createdAt: "2024-12-16T10:00:00Z",
  },
  {
    id: "p6",
    farmerId: "f3",
    farmerName: "Mohamed Bangura",
    farmerLocation: "Kenema, Eastern Province",
    farmerPhone: "+232 78 345 678",
    name: "Sweet Potatoes",
    category: "Tubers",
    quantity: "250",
    unit: "kg",
    pricePerUnit: 4000,
    description: "Orange-fleshed sweet potatoes, rich in vitamins. Fresh from the farm.",
    harvestDate: "2024-12-20",
    imageUrl: "/sweet-potatoes-orange.jpg",
    status: "available",
    createdAt: "2024-12-21T10:00:00Z",
  },
]

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: "c1",
    farmerId: "f1",
    farmerName: "John Kamara",
    buyerId: "b1",
    buyerName: "Sarah Koroma",
    produceId: "p1",
    produceName: "Rice",
    lastMessage: "Yes, I can deliver to Freetown. The transport cost will be Le 50,000.",
    lastMessageTime: "2024-12-26T14:30:00Z",
    unreadCount: 0,
  },
  {
    id: "c2",
    farmerId: "f2",
    farmerName: "Fatmata Sesay",
    buyerId: "b2",
    buyerName: "Abdul Jalloh",
    produceId: "p2",
    produceName: "Cassava",
    lastMessage: "Good afternoon. I am interested in your cassava. Can we discuss pricing?",
    lastMessageTime: "2024-12-26T12:15:00Z",
    unreadCount: 1,
  },
]

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: "m1",
    conversationId: "c1",
    senderId: "b1",
    senderName: "Sarah Koroma",
    senderRole: "buyer",
    receiverId: "f1",
    content: "Good morning! I am interested in buying 200kg of your rice. Is it still available?",
    timestamp: "2024-12-26T09:00:00Z",
    read: true,
  },
  {
    id: "m2",
    conversationId: "c1",
    senderId: "f1",
    senderName: "John Kamara",
    senderRole: "farmer",
    receiverId: "b1",
    content: "Good morning! Yes, the rice is still available. The price is Le 8,000 per kg.",
    timestamp: "2024-12-26T09:15:00Z",
    read: true,
  },
  {
    id: "m3",
    conversationId: "c1",
    senderId: "b1",
    senderName: "Sarah Koroma",
    senderRole: "buyer",
    receiverId: "f1",
    content: "That sounds good. Can you deliver to Freetown?",
    timestamp: "2024-12-26T14:00:00Z",
    read: true,
  },
  {
    id: "m4",
    conversationId: "c1",
    senderId: "f1",
    senderName: "John Kamara",
    senderRole: "farmer",
    receiverId: "b1",
    content: "Yes, I can deliver to Freetown. The transport cost will be Le 50,000.",
    timestamp: "2024-12-26T14:30:00Z",
    read: true,
  },
  {
    id: "m5",
    conversationId: "c2",
    senderId: "b2",
    senderName: "Abdul Jalloh",
    senderRole: "buyer",
    receiverId: "f2",
    content: "Good afternoon. I am interested in your cassava. Can we discuss pricing?",
    timestamp: "2024-12-26T12:15:00Z",
    read: false,
  },
]
