CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text,
    "GoogleId" character varying(128),
    "Role" character varying(20) NOT NULL,
    "Phone" character varying(20),
    "Location" character varying(100),
    "FarmSize" text,
    "FarmingExperience" text,
    "BusinessName" text,
    "BusinessType" text,
    "IsEmailVerified" boolean NOT NULL,
    "EmailVerificationToken" text,
    "EmailVerificationExpiry" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Produces" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FarmerId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "Description" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "Quantity" integer NOT NULL,
    "Location" character varying(100),
    "ImageUrl" text,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Produces" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produces_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "ProduceId" integer,
    "Content" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Produces_ProduceId" FOREIGN KEY ("ProduceId") REFERENCES "Produces" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Messages_Users_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuyerId" integer NOT NULL,
    "FarmerId" integer NOT NULL,
    "ProduceId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" character varying(50) NOT NULL,
    "AccountNumber" character varying(50) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Produces_ProduceId" FOREIGN KEY ("ProduceId") REFERENCES "Produces" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Users_BuyerId" FOREIGN KEY ("BuyerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Users_FarmerId" FOREIGN KEY ("FarmerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Messages_ProduceId" ON "Messages" ("ProduceId");

CREATE INDEX "IX_Messages_ReceiverId" ON "Messages" ("ReceiverId");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Orders_BuyerId" ON "Orders" ("BuyerId");

CREATE INDEX "IX_Orders_FarmerId" ON "Orders" ("FarmerId");

CREATE INDEX "IX_Orders_ProduceId" ON "Orders" ("ProduceId");

CREATE INDEX "IX_Produces_FarmerId" ON "Produces" ("FarmerId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260726131549_InitialSupabasePostgres', '8.0.4');

COMMIT;

